config/routes.rb
Rails.application.routes.draw do
	root "movies#index"
	resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	def flop?
		total_gross.blank? || total_gross < 5000000
	end

	def self.released
		where("released_on <= ?", Time.now).order("released_on desc")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movies = Movie.released
	end

	def show
		@movie = Movie.find(params[:id])
	end

	def edit	
		@movie = Movie.find(params[:id])
	end

	def update
	  @movie = Movie.find(params[:id])
	  @movie.update(movie_params)
	  redirect_to @movie
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.new(movie_params)
		@movie.save
		redirect_to @movie
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to movies_url
	end



	private
	  def movie_params
	    params.require(:movie).permit(
	    		:title, 
	    		:description, 
	    		:rating, 
	    		:released_on, 
	    		:total_gross,
	    		:cast,
	    		:director, 
	    		:duration,
	    		:image_file_name
	    	)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	def format_total_gross(movie)
		if movie.flop?
			content_tag(:strong, 'Flop!')
			# this also works: "<strong>Flop!</strong>".html_safe
		else
			number_to_currency(movie.total_gross)
		end
	end
	def image_for(movie)
	  if movie.image_file_name.blank?
	    #image_tag('adele.jpg')
	  else
	    image_tag(movie.image_file_name)
	  end
	end
end

app/views/layouts/_footer.html.erb
<footer style="text-align: center; padding: 5px; color: #237CBE; background: #F0F0F0">
  <p>
    Copyright &copy; 2016
    <%= link_to 'The Pragmatic Studio','http://pragmaticstudio.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header style="padding: 5px; color: #F0F0F0; background: #237CBE;">
  <h1>Super-Heroic Flix</h1>
</header>

app/views/layouts/_sidebar.html.erb
<aside style="float: right; background: #F0F0F0; width: 200px;">
  <nav>
    <ul>
      <li>
        <%= link_to 'All Movies', movies_path %>
      </li>
      <li>
        <%= link_to 'Add New Movie', new_movie_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head style="background:pink">
    <title>Flix testing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render "layouts/header" %>
  	<%= render "layouts/sidebar" %>

    <%= yield %>
  	<%= render "layouts/footer" %>

    
  </body>
</html>

app/views/movies/_footer.html.erb
<h3 style="text-align: center">Julia's app</h3>

app/views/movies/_form.html.erb
<h1>Editings Movie: <%= @movie.title %></h1>

<%= form_for(@movie) do |f| %>
	<p>
		<%= f.label :title %><br/>
		<%= f.text_field :title, autofocus: true %>
	</p>
	<p>
		<%= f.label :cast %><br/>
		<%= f.text_field :cast %>
	</p>
	<p>
		<%= f.label :director %><br/>
		<%= f.text_field :director %>
	</p>	
	<p>
		<%= f.label :duration %><br/>
		<%= f.text_field :duration %>
	</p>
	<p>
		<%= f.label :image_file_name %><br/>
		<%= f.text_field :image_file_name %>
	</p>
	<p>
		<%= f.label :description %><br/>
		<%= f.text_area :description, cols:40, rows:7 %>
	</p>
	<p>
		<%= f.label :rating %><br/>
		<%= f.text_field :rating, size:5 %>
	</p>
	<p>
		<%= f.label :released_on %><br/>
		<%= f.date_field :released_on %>
	</p>
	<p>
		<%= f.label :total_gross %><br/>
		<%= f.number_field :total_gross %>
	</p>
	<p>
		<%= f.submit %>
		<%= link_to "Cancel", movies_path %>
	</p>
<% end %>

app/views/movies/edit.html.erb
<h1>Editings Movie: <%= @movie.title %></h1>

<%= render 'form' %>

<%= render 'footer' %>

app/views/movies/index.html.erb
<h1><%= pluralize(@movies.size, 'Movie') %></h1>
      <h2><%= link_to("Add new movie", new_movie_path) %></h2>
<% @movies.each do |movie| %>
  <article>
    <header>
      <h2><%= link_to movie.title, movie %></h2>
      <h2><%= image_for(movie) %></h2>
      <h3><%= movie.cast %></h3>
    </header>
    <p>
      <%= truncate(movie.description, length:40, seperator: ' ') %>
    </p>
    <table>
      <tr>
        <th>Released:</th>
        <td><%=movie.released_on%></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= movie.duration  %></td>
      </tr>      <tr>
        <th>Rating:</th>
        <td><%= movie.rating %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
        <td><%= format_total_gross(movie) %></td>
      </tr>
    </table>
  </article>
<% end %>

app/views/movies/new.html.erb
<p>New form for a movie in browser round six</p>

<%= render 'form' %>

<%= render 'footer' %>

app/views/movies/show.html.erb
<article>
  <header>
    <h1><%= @movie.title %></h1>
  </header>
  <h2>Description</h2>
  <p>
    <%= @movie.description %>
  </p>
  <h3>Rating</h3>
  <p>
    <%= @movie.rating %>
  </p>
  <h3>Released On</h3>
  <p>
    <%= @movie.released_on %>
  </p>
  <h3>Total Gross</h3>
  <p>
    <%= format_total_gross(@movie) %>
  </p>
  h3>Cast</h3>
<p>
  <%= @movie.cast %>
</p>

<h3>Director</h3>
<p>
  <%= @movie.director %>
</p>

<h3>Duration</h3>
<p>
  <%= @movie.duration %>
</p>


<p>testing sssssss</p>
</article>

<nav>
  <p>navigation</p>
  <%= link_to("View All Movies", root_path) %>
  <%= link_to("Edit", edit_movie_path) %> 
  <%= link_to "Delete", movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' } %>
  </nav>